set CURRENT_DIRECTORY=%1
set CURRENT_BINARY_DIRECTORY=%2

set CURRENT_DIRECTORY=%CURRENT_DIRECTORY:/=\%
set CURRENT_BINARY_DIRECTORY=%CURRENT_BINARY_DIRECTORY:/=\%

xcopy /s  %CURRENT_DIRECTORY% %CURRENT_BINARY_DIRECTORY%  /y